---
logging:
  level: INFO
  loggers:
    org.example: DEBUG

jwtConfiguration:
  secretKey: theBestKeptSecretIsToPretendThatThereIsntOne
  tokenExpirationMinutes: 60

#jersey:
#  packages:
#    - org.example.api
